name: Package Flutter Run
on:
  push:
    branches:
      - main

jobs:
  analyze-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pana analyzer
        uses: axel-op/dart-package-analyzer@v3
        id: pana-analysis

  check-scores:
    runs-on: ubuntu-latest
    needs: analyze-package
    steps:
      - name: Checking pana scores
        env:
          TOTAL: ${{ needs.analyze-package.outputs.total }}
          TOTAL_MAX: ${{ needs.analyze-package.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 50 )); then
            echo "Score too low!"
            exit 1
          fi

          echo "Score is satisfactory. Proceeding to build."

  build-and-publish:
    runs-on: ubuntu-latest
    needs: check-scores
    if: needs.check-scores.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Check for formatting issues
        run: dart format --set-exit-if-changed .

      - name: Statically analyze Dart code
        run: flutter analyze .

      - name: Run widget tests
        run: flutter test

      - name: Publish package dry run
        run: flutter pub publish --dry-run
