name: Package Flutter Run
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    # This job will run on ubuntu virtual machine
    if: github.ref != 'refs/heads/stable'
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Integrate Dart/Flutter Package Analyzer
      - uses: axel-op/dart-package-analyzer@v3
        # set an id for the current step
        id: package-analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Check the scores and exit if the total score in percentage is below 50
      - name: Check scores
        env:
          TOTAL: ${{ steps.package-analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.package-analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 50 ))
          then
            echo Score too low!
            exit 1
          fi

      # Pub dry run.
      - run: flutter doctor --v
      - run: sudo flutter pub publish --dry-run
