name: Trigger PubDev Release

on:
  push:
    branches:
      - dev

jobs:
  analyze-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pana analyzer
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        id: pana-analysis

      - name: Set outputs
        id: set-outputs
        run: |
          echo "TOTAL=${{ steps.pana-analysis.outputs.total }}"
          echo "TOTAL_MAX=${{ steps.pana-analysis.outputs.total_max }}"

      - name: Checking pana scores
        env:
          TOTAL: ${{ steps.pana-analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.pana-analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL ))
          if (( $PERCENTAGE < 110 )); then
            echo "Score too low!"
            exit 1
          fi
          echo "Score is satisfactory. Proceeding to build."

  build-and-publish:
    runs-on: ubuntu-latest
    needs: analyze-package
    if: ${{ needs.analyze-package.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Flutter version Check
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Check for formatting issues
        run: dart format --set-exit-if-changed .

      - name: Statically analyze Dart code
        run: flutter analyze .

      - name: Run widget tests
        run: flutter test

      - name: Publish package dry run
        run: flutter pub publish --dry-run

      - name: Extract version from pubspec.yaml
        id: extract-version
        run: |
          VERSION=$(grep version: pubspec.yaml | awk '{print $2}' | tr -d "'")
          if [[ -z "$VERSION" ]]; then
            echo "Error: VERSION variable is empty. Skipping tag creation."
            exit 1
          fi
          echo "Extracted version: $VERSION"
          echo "VERSION= ${{ steps.extract-version.outputs.VERSION }}"

  release-on-push:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from pubspec.yaml
        id: extract-version
        run: |
          VERSION=$(grep version: pubspec.yaml | awk '{print $2}' | tr -d "'")
          echo "Extracted version: $VERSION"

      - name: Set up Git user
        uses: fregante/setup-git-user@v2

      - name: Create and push tag
        if: ${{ needs.analyze-package.result == 'success' }}
        run: |
          git tag -a "v${{ steps.extract-version.outputs.VERSION }}" -m "Release v${{ steps.extract-version.outputs.VERSION }}"
          git push origin "v${{ steps.extract-version.outputs.VERSION }}"
